build

diff --git a/AnyKernel3/META-INF/com/google/android/update-binary b/AnyKernel3/META-INF/com/google/android/update-binary
--- a/AnyKernel3/META-INF/com/google/android/update-binary
+++ b/AnyKernel3/META-INF/com/google/android/update-binary
@@ -29,7 +29,7 @@ ui_printfile() {
   done < $1;
 }
 show_progress() { echo "progress $1 $2" >> $OUTFD; }
-file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
+file_getprop() { $BB grep "^$2=" "$1" | $BB tail -n1 | $BB cut -d= -f2-; }
 find_slot() {
   local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
   [ "$slot" ] || slot=$($BB grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | $BB cut -d\  -f1 | $BB cut -d= -f2);
@@ -52,25 +52,26 @@ mount_apex() {
   [ -d /system_root/system/apex ] || return 1;
   local apex dest loop minorx num var;
   setup_mountpoint /apex;
+  $BB mount -t tmpfs tmpfs /apex -o mode=755 && $BB touch /apex/apextmp;
   minorx=1;
   [ -e /dev/block/loop1 ] && minorx=$($BB ls -l /dev/block/loop1 | $BB awk '{ print $6 }');
   num=0;
   for apex in /system_root/system/apex/*; do
-    dest=/apex/$($BB basename $apex .apex);
-    case $dest in
-      *.current|*.release) dest=$(echo $dest | $BB rev | $BB cut -d. -f2- | $BB rev);;
-    esac;
+    dest=/apex/$($BB basename $apex | $BB sed -E -e 's;\.apex$|\.capex$;;' -e 's;\.current$|\.release$;;');
     $BB mkdir -p $dest;
     case $apex in
-      *.apex)
+      *.apex|*.capex)
+        $BB unzip -qo $apex original_apex -d /apex;
+        [ -f /apex/original_apex ] && apex=/apex/original_apex;
         $BB unzip -qo $apex apex_payload.img -d /apex;
+        $BB mv -f /apex/original_apex $dest.apex 2>/dev/null;
         $BB mv -f /apex/apex_payload.img $dest.img;
         $BB mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
         if [ $? != 0 ]; then
           while [ $num -lt 64 ]; do
             loop=/dev/block/loop$num;
-            ($BB mknod $loop b 7 $((num * minorx));
-            $BB losetup $loop $dest.img) 2>/dev/null;
+            [ -e $loop ] || $BB mknod $loop b 7 $((num * minorx));
+            $BB losetup $loop $dest.img 2>/dev/null;
             num=$((num + 1));
             $BB losetup $loop | $BB grep -q $dest.img && break;
           done;
@@ -89,9 +90,9 @@ mount_apex() {
   $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB sed 's; /;=/;'); unset export;
 }
 umount_apex() {
-  [ -d /apex/com.android.runtime ] || return 1;
+  [ -d /apex ] || return 1;
   local dest loop var;
-  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB awk '{ print $2 }'); do
+  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc 2>/dev/null | $BB awk '{ print $2 }'); do
     if [ "$(eval echo \$OLD_$var)" ]; then
       eval $var=\$OLD_${var};
     else
@@ -100,28 +101,32 @@ umount_apex() {
     unset OLD_${var};
   done;
   for dest in $($BB find /apex -type d -mindepth 1 -maxdepth 1); do
-    if [ -f $dest.img ]; then
-      loop=$($BB mount | $BB grep $dest | $BB cut -d\  -f1);
-    fi;
-    ($BB umount -l $dest;
-    $BB losetup -d $loop) 2>/dev/null;
+    loop=$($BB mount | $BB grep $dest | $BB grep loop | $BB cut -d\  -f1);
+    $BB umount -l $dest;
+    [ "$loop" ] && $BB losetup -d $loop;
   done;
+  [ -f /apex/apextmp ] && $BB umount /apex;
   $BB rm -rf /apex 2>/dev/null;
 }
 mount_all() {
+  local byname mount slot system;
   if ! is_mounted /cache; then
     $BB mount /cache 2>/dev/null && UMOUNT_CACHE=1;
   fi;
   if ! is_mounted /data; then
     $BB mount /data && UMOUNT_DATA=1;
   fi;
-  ($BB mount -o ro -t auto /vendor;
-  $BB mount -o ro -t auto /product;
-  $BB mount -o ro -t auto /persist) 2>/dev/null;
+  (for mount in /vendor /product /system_ext /persist; do
+    $BB mount -o ro -t auto $mount;
+  done) 2>/dev/null;
   setup_mountpoint $ANDROID_ROOT;
   if ! is_mounted $ANDROID_ROOT; then
     $BB mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
   fi;
+  byname=bootdevice/by-name;
+  [ -d /dev/block/$byname ] || byname=$($BB find /dev/block/platform -type d -name by-name 2>/dev/null | $BB head -n1 | $BB cut -d/ -f4-);
+  [ -d /dev/block/mapper ] && byname=mapper;
+  [ -e /dev/block/$byname/system ] || slot=$(find_slot);
   case $ANDROID_ROOT in
     /system_root) setup_mountpoint /system;;
     /system)
@@ -135,28 +140,24 @@ mount_all() {
       if [ $? != 0 ]; then
         ($BB umount /system;
         $BB umount -l /system) 2>/dev/null;
-        if [ -d /dev/block/mapper ]; then
-          [ -e /dev/block/mapper/system ] || local slot=$(find_slot);
-          $BB mount -o ro -t auto /dev/block/mapper/vendor$slot /vendor;
-          $BB mount -o ro -t auto /dev/block/mapper/product$slot /product 2>/dev/null;
-          $BB mount -o ro -t auto /dev/block/mapper/system$slot /system_root;
-        else
-          [ -e /dev/block/bootdevice/by-name/system ] || local slot=$(find_slot);
-          ($BB mount -o ro -t auto /dev/block/bootdevice/by-name/vendor$slot /vendor;
-          $BB mount -o ro -t auto /dev/block/bootdevice/by-name/product$slot /product;
-          $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist$slot /persist) 2>/dev/null;
-          $BB mount -o ro -t auto /dev/block/bootdevice/by-name/system$slot /system_root;
-        fi;
+        $BB mount -o ro -t auto /dev/block/$byname/system$slot /system_root;
       fi;
     ;;
   esac;
+  [ -f /system_root/system/build.prop ] && system=/system;
+  for mount in /vendor /product /system_ext; do
+    if ! is_mounted $mount && [ -L /system$mount -o -L /system_root$system$mount ]; then
+      setup_mountpoint $mount;
+      $BB mount -o ro -t auto /dev/block/$byname$mount$slot $mount;
+    fi;
+  done;
   if is_mounted /system_root; then
     mount_apex;
-    if [ -f /system_root/build.prop ]; then
-      $BB mount -o bind /system_root /system;
-    else
-      $BB mount -o bind /system_root/system /system;
-    fi;
+    $BB mount -o bind /system_root$system /system;
+  fi;
+  if ! is_mounted /persist && [ -e /dev/block/bootdevice/by-name/persist ]; then
+    setup_mountpoint /persist;
+    $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist /persist;
   fi;
 }
 umount_all() {
@@ -172,7 +173,7 @@ umount_all() {
   fi;
   umount /vendor; # busybox umount /vendor breaks recovery on some hacky devices
   umount -l /vendor;
-  for mount in /mnt/system /mnt/vendor /product /mnt/product /persist; do
+  for mount in /mnt/system /mnt/vendor /product /mnt/product /system_ext /mnt/system_ext /persist; do
     $BB umount $mount;
     $BB umount -l $mount;
   done;
@@ -202,7 +203,7 @@ setup_env() {
   if [ ! "$(getprop 2>/dev/null)" ]; then
     getprop() {
       local propdir propfile propval;
-      for propdir in / /system_root /system /vendor /odm /product; do
+      for propdir in / /system_root /system /vendor /product /system_ext /odm; do
         for propfile in default.prop build.prop; do
           if [ "$propval" ]; then
             break 2;
@@ -233,7 +234,7 @@ restore_env() {
   unset OLD_LD_PATH OLD_LD_PRE OLD_LD_CFG;
   umount_all;
   [ -L /etc_link ] && $BB rm -rf /etc/*;
-  (for dir in /apex /system /system_root /etc; do
+  (for dir in /etc /apex /system_root /system /vendor /product /system_ext /persist; do
     if [ -L "${dir}_link" ]; then
       rmdir $dir;
       $BB mv -f ${dir}_link $dir;
@@ -242,7 +243,7 @@ restore_env() {
   $BB umount -l /dev/random) 2>/dev/null;
 }
 debugging() {
-  case $(basename "$ZIPFILE" .zip) in
+  case $($BB basename "$ZIPFILE" .zip) in
     *-debugging)
       ui_print " " "Creating debugging archive in $DIR...";
       [ -f /tmp/recovery.log ] && local log=/tmp/recovery.log;
@@ -271,17 +272,17 @@ do_devicecheck() {
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
   vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
-  for testname in $(file_getprop anykernel.sh 'device.name.*'); do
+  for testname in $($BB grep '^device.name.*=' anykernel.sh | $BB cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "- OK ! ";
+        ui_print "$testname" " ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort "! Unsupported device , This Device is $devicename . Aborting... !";
+    abort " " "Unsupported device. Aborting...";
   fi;
 }
 int2ver() {
@@ -296,7 +297,7 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "- Checking Android Version...";
+  ui_print "Checking Android version...";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -314,11 +315,10 @@ do_versioncheck() {
       fi;
     done;
   fi;
-  ui_print "- Android Version: $android_ver ";
   if [ "$supported" ]; then
-	ui_print "- OK !";
+    ui_print "$android_ver" " ";
   else
-    abort "! Unsupported Android version, This Kernel is only for Android $supported_ver . Aborting... !";
+    abort " " "Unsupported Android version. Aborting...";
   fi;
 }
 do_levelcheck() {
@@ -339,13 +339,13 @@ do_levelcheck() {
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
-    ui_print ">> $android_lvl <<";
+    ui_print "$android_lvl" " ";
   else
-    abort "! Unsupported Android security patch level. Aborting... !";
+    abort " " "Unsupported Android security patch level. Aborting...";
   fi;
 }
 dump_moduleinfo() {
-cat <<EOF > $1;
+$BB cat <<EOF > $1;
 name=AK3 Helper Module
 version=$($BB awk '{ print $3 }' $AKHOME/vertmp) $($BB grep -oE '#.[0-9]' $AKHOME/vertmp)
 versionCode=1
@@ -354,7 +354,7 @@ description=$KERNEL_STRING
 EOF
 }
 dump_moduleremover() {
-cat <<'EOF' > $1;
+$BB cat <<'EOF' > $1;
 #!/system/bin/sh
 MODDIR=${0%/*};
 if [ "$(cat /proc/version)" != "$(cat $MODDIR/version)" ]; then
@@ -368,18 +368,18 @@ do_modules() {
   if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
     cd $AKHOME/modules;
     ui_print " " "Creating kernel helper Magisk module...";
-    if [ -d /data/adb/magisk -a -f $AKHOME/split_img/.magisk ]; then
+    if [ -d /data/adb/magisk -a -f $AKHOME/magisk_patched ]; then
       umask=$(umask);
       umask 022;
       moddir=/data/adb/modules/ak3-helper;
       $BB rm -rf $moddir;
-      mkdir -p system $moddir;
+      $BB mkdir -p system $moddir;
       ($BB mv -f product system;
       $BB mv -f vendor system) 2>/dev/null;
       $BB cp -rLf * $moddir;
       dump_moduleinfo $moddir/module.prop;
       dump_moduleremover $moddir/post-fs-data.sh;
-      cp -f $AKHOME/vertmp $moddir/version;
+      $BB cp -f $AKHOME/vertmp $moddir/version;
       umask $umask;
     else
       ui_print "Magisk installation not found. Skipped!";
@@ -399,7 +399,7 @@ do_modules() {
       ($BB mount -o rw,remount -t auto /vendor;
       $BB mount -o rw,remount -t auto /product) 2>/dev/null;
     fi;
-    for module in $(find . -name '*.ko'); do
+    for module in $($BB find . -name '*.ko'); do
       modtarget=$POSTINSTALL$(echo $module | $BB cut -c2-);
       if [ ! -e $modtarget ]; then
         case $module in
@@ -411,7 +411,7 @@ do_modules() {
       if is_mounted $modtarget; then
         $BB mount -o rw,remount -t auto $modtarget;
       fi;
-      mkdir -p $(dirname $modtarget);
+      $BB mkdir -p $($BB dirname $modtarget);
       $BB cp -rLf $module $modtarget;
       $BB chown 0:0 $modtarget;
       $BB chmod 644 $modtarget;
@@ -429,64 +429,6 @@ do_modules() {
     fi;
   fi;
   cd $AKHOME;
-}
-
-AddSpectrum(){
-  cd $AKHOME;
-  # custom script for spectrum
-  $BB mount -o rw,remount -t auto /system;
-  $BB mount -o rw,remount -t auto /vendor 2>/dev/null;
-
-  # add spectrum support
-  if [ -e $AKHOME/init.spectrum.rc ];then
-  ui_print "- Backing up Old Script in Progress...";
-    if [ ! -e /vendor/etc/init/hw/init.qcom.rc.backup ];then
-      cp -af /vendor/etc/init/hw/init.qcom.rc /vendor/etc/init/hw/init.qcom.rc.backup
-    fi
-    if [ ! -e /vendor/etc/init/hw/init.spectrum.rc.backup ];then
-      cp -af /vendor/etc/init/hw/init.spectrum.rc /vendor/etc/init/hw/init.spectrum.rc.backup
-    fi
-	ui_print "- Patching init.qcom.rc...";
-    grep "import /init.spectrum.rc" /vendor/etc/init/hw/init.qcom.rc >/dev/null | sed -i '/import \/init.spectrum.rc/d' /vendor/etc/init/hw/init.qcom.rc
-    grep "import init.spectrum.rc" /vendor/etc/init/hw/init.qcom.rc >/dev/null | sed -i '/import init.spectrum.rc/d' /vendor/etc/init/hw/init.qcom.rc
-    grep "import /vendor/etc/init/hw/init.spectrum.rc" /vendor/etc/init/hw/init.qcom.rc >/dev/null || sed -i '1,/.*import.*/s/.*import.*/import \/vendor\/etc\/init\/hw\/init.spectrum.rc\n&/' /vendor/etc/init/hw/init.qcom.rc
-    ui_print "- Patching Spectrum Script...";
-	cp -af $AKHOME/init.spectrum.rc /vendor/etc/init/hw/
-    chmod -R 644 /vendor/etc/init/hw/init.spectrum.rc
-    # cprofile remover
-    if [ -e /system/xbin/cprofile ];then
-      rm -rf /system/xbin/cprofile
-      ui_print "remove /system/xbin/cprofile"
-    fi
-    if [ -e /system/bin/cprofile ];then
-      rm -rf /system/bin/cprofile
-      ui_print "remove /system/bin/cprofile"
-    fi
-    if [ -e /vendor/bin/cprofile ];then
-      rm -rf /vendor/bin/cprofile
-      ui_print "remove /vendor/bin/cprofile"
-    fi
-    if [ -e /system/init.spectrum.rc ];then
-      rm -rf /system/init.spectrum.rc
-      ui_print "remove /system/init.spectrum.rc"
-    fi
-    if [ -e /system/init.spectrum.sh ];then
-      rm -rf /system/init.spectrum.sh
-      ui_print "remove /system/init.spectrum.sh"
-    fi
-  else
-    if [ -e /vendor/etc/init/hw/init.spectrum.rc ];then
-      rm -rf /vendor/etc/init/hw/init.spectrum.rc
-	  ui_print "- Removing old Spectrum Script..."
-    fi
-    if [ -e /vendor/etc/init/hw/init.qcom.rc.backup ];then
-      cp -af /vendor/etc/init/hw/init.qcom.rc.backup /vendor/etc/init/hw/init.qcom.rc
-      rm -rf /vendor/etc/init/hw/init.qcom.rc.backup
-      grep "import /vendor/etc/init/hw/init.spectrum.rc" /vendor/etc/init/hw/init.qcom.rc >/dev/null | sed -i '/import \/vendor\/etc\/init\/hw\/init.spectrum.rc/d' /vendor/etc/init/hw/init.qcom.rc
-    fi
-  fi
-  $BB mount -o ro,remount -t auto /system;
-  $BB mount -o ro,remount -t auto /vendor 2>/dev/null;
 }
 
 show_progress 1.34 4;
@@ -519,38 +461,27 @@ fi;
 
 if [ -f banner ]; then
   ui_printfile banner;
-  ui_print " ";
+  ui_print " " " ";
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
-KERNEL_FOR="$(file_getprop anykernel.sh kernel.for)";
-KERNEL_COMPILER="$(file_getprop anykernel.sh kernel.compiler)";
-KERNEL_MADE="$(file_getprop anykernel.sh kernel.made)";
-KERNEL_VERSION="$(file_getprop anykernel.sh kernel.version)";
-BUILD_DATE="$(file_getprop anykernel.sh build.date)";
-MESSAGE_WORD="$(file_getprop anykernel.sh message.word)";
-DEVICE_NAME="$(file_getprop anykernel.sh device.name3)";
-ui_print "-- Kernel Name    : $KERNEL_STRING";
-ui_print "-- Kernel Version : $KERNEL_VERSION";
-ui_print "-- Variant        : $KERNEL_FOR";
-ui_print "-- Compiler       : $KERNEL_COMPILER";
-ui_print "-- Device         : $DEVICE_NAME";
-ui_print "-- Build Date     : $BUILD_DATE";
-ui_print "-- Build by       : $KERNEL_MADE";
-ui_print "_________________________________________________" " ";
+ui_print "$KERNEL_STRING";
 if [ -f version ]; then
   ui_print " ";
   ui_printfile version;
   ui_print " ";
 fi;
-ui_print "- Preparing Environment Setup ...";
+ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " ";
+$BB grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
+ui_print " ";
+
 setup_env;
 
 do_devicecheck;
 do_versioncheck;
 do_levelcheck;
 
-ui_print "Flashing Persephone Kernel...";
+ui_print "Installing...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
@@ -560,15 +491,11 @@ fi;
 
 do_modules;
 
-# custom script for add spectrum support to kernel
-AddSpectrum;
-
 debugging;
 restore_env;
+
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print "- Done";
-ui_print " " "_________________________________________________";
-ui_print " " "$MESSAGE_WORD" "_________________________________________________" " ";
+ui_print " " " " "Done!";
